import React, { useEffect } from 'react';

const FinishReg = (props) => {

    useEffect(() => {
        const togglePassword = document.getElementById('toggle-password');
        togglePassword.addEventListener('click', () => {
            const password = document.getElementById('password');
            togglePassword.classList.contains('fa-eye') ?
            password.setAttribute('type', 'text') : password.setAttribute('type', 'password');
            togglePassword.classList.toggle('fa-eye');
            togglePassword.classList.toggle('fa-eye-slash');
        })
    })

    const handleSubmit = (e) => {

        const form = document.getElementById("admin-reg-form");
        const successDiv = document.getElementById("success-div");
        const failureDiv = document.getElementById("failure-div");
        const loadingDiv = document.getElementById("loading-div");
        const submitBtn = document.getElementById("submit-btn");

            e.preventDefault();
            const formData = new FormData(form);
            const name = formData.get('name');
            const email = formData.get('email');
            const password = formData.get('password');
            const secretKey = formData.get('secretKey');
            successDiv.style.display = "none";
            failureDiv.style.display = "none";
            loadingDiv.style.display = "block";
            submitBtn.style.display = "none";

            const Params = {
				headers: {
					"Content-type": "application/JSON",
				},
				body: JSON.stringify({
                    name,
                    email,
                    password,
                    secretKey,
				}),
				method: "POST",
			};

            async function registerUser(params){
             const res = await fetch("http://localhost:7890/api/user/register-admin", params);
             const data = await res.json();
             console.log(data)
             console.log(data.error)
             if (data.success){
                 successDiv.innerHTML = data.success + " <a href='/admin-login'> Continue to Login</a>";
                 successDiv.style.display = "block";
                 failureDiv.style.display = "none";
                 submitBtn.style.display = "none";
                 form.reset();
             }
             if (data.error){
                failureDiv.innerHTML = data.error;
                failureDiv.style.display = "block";
                successDiv.style.display = "none";
                submitBtn.style.display = "block";
             }
             loadingDiv.style.display = "none";
            }
            try {
                registerUser(Params);
            } catch (err) {
                successDiv.style.display = "none";
                failureDiv.innerText = err.error;
                failureDiv.style.display = "block";
                loadingDiv.style.display = "none";
                submitBtn.style.display = "block";
            }
    }

    return (
        <>
            <div className="bg-color"></div>
            <div className="container container-xl continue-donor-reg">
                <div className="register-nav" data-aos="fade-down">
                    <a href="/"><i className="fa fa-angle-left fa-2x"></i> Go to Home</a>
                    <a href="/admin-login">Go to Login <i className="fa fa-angle-right fa-2x"></i> </a>
                </div>

                <div className="continue-registration">
                    <div className="register-info" data-aos="fade-right">
                        <h1><strong>Welcome to OneShare Admin!</strong></h1>
                        <p>To register as admin, you'll a secret key only generated by OneShare administration, and a verified email.</p>
                        <p>As an admin, you'll be able to approve donations and requests as well as visualize user traffic on OneShare.</p>
                        <div className="oneshare-logo">
                            <img src="images/Logo-blue.svg" alt="oneshare logo" />
                        </div>
                    </div>

                    <div className="register-form" data-aos="fade-left">
                        <h2 className="text-center"><strong>Admin Registration</strong></h2>
                        <div className="underline"></div>
                        <p className="text-center"> Register as an admin on OneShare.</p>
                        <form id="admin-reg-form" onSubmit={handleSubmit}>
                            <input className="mb-4" type="name" name="name" placeholder="FirstName LastName"
                            autoComplete="false" autoFocus required minLength="3"
                            maxLength="30" pattern="[a-zA-Z]{3,}\s[a-zA-Z]{3,}"/>
                            <input className="mb-4" type="email" name="email" placeholder="Email"
                            autoComplete="false" required minLength="6"
                            maxLength="40"/>
                            <div className="w-100 mb-4 text-center">
                                <input type="password" name="password" id="password" placeholder="Password" autoComplete="false" required/>
                                <span><i className="fa fa-eye" id="toggle-password"></i></span>
                            </div>
                            <input className="mb-4" type="name" name="secretKey" placeholder="Secret Key"
                            autoComplete="false" required minLength="8"
                            maxLength="20" pattern="[a-zA-Z]{3,}\s[a-zA-Z]{3,}"/>

                            <div id="loading-div"></div>
                            <div id="success-div" className="text-success"></div>
                            <div id="failure-div" className="text-danger mb-3"></div>
                            <button type="submit" id="submit-btn" className="completed">
                                <strong>Finish</strong>
                            </button>
                        </form>
                    </div>
                  <div className="bg-color-device" id="finish-page"></div>
                </div>
            </div>
        </>
    )
};
export default FinishReg;